config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords'
  }

  # Routes for authenticated users
  authenticate :user do
    resources :departments
    resources :employees
    resources :bills do
      member do
        patch :approve
        patch :decline
      end
    end
    root 'bills#index', as: :authenticated_root
  end

  # Routes for unauthenticated users
  root 'home#index'
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :set_employee, only: %i[show edit update destroy]

  def index
    @employees = User.all.order(created_at: :asc)
  end

  def show; end

  def new
    @employee = User.new
  end

  def create
    @employee = User.new(employee_params)
    if @employee.save!
      redirect_to employees_path, notice: 'Employee created successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    @employee.update(employee_params)
    if @employee
      redirect_to employees_path, notice: 'Employee updated successfully'
    else
      render :edit
    end
  end

  def destroy
    return  if @employee.blank?

    @employee.destroy
    redirect_to employees_path, notice: 'Employee deleted successfully'
  end

  private

  def employee_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :role, :designation, :department_id)
  end

  def set_employee
    @employee = User.find_by(id: params[:id])
  end

  def is_admin?
    redirect_to root_path notice: 'Access Denied' if current_user.employee_permission?
  end
end

app/views/employees/_form.html.erb
<%= form_with(model: user, url: url, method: method_name, local: true) do |f| %>
  <div class="row g-3 d-flex align-items-center justify-content-center ">
    <div class="col-md-6">
      <%= f.label :first_name, class: 'form-label' %><span style="color: red">*</span><br />
      <%= f.text_field :first_name, class: 'form-control' %>
      <% user.errors.full_messages_for(:first_name).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :last_name, class: 'form-label' %><br />
      <%= f.text_field :last_name, class: 'form-control' %>
      <% user.errors.full_messages_for(:last_name).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :email, class: 'form-label' %><span style="color: red">*</span><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :password, class: 'form-label' %><span style="color: red">*</span>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :password_confirmation, class: 'form-label' %><span style="color: red">*</span><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
      <% user.errors.full_messages_for(:password_confirmation).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :designation, class: 'form-label' %><br />
      <%= f.text_field :designation, class: 'form-control' %>
      <% user.errors.full_messages_for(:designation).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :department, class: 'form-label' %><span style="color: red">*</span><br />
      <%= f.collection_select :department_id, Department.all, :id, :name, { prompt: 'Select Department' }, { class: 'form-control' }%>
      <% user.errors.full_messages_for(:department).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-6">
      <%= f.label :role, class: 'form-label' %><span style="color: red">*</span><br />
      <%= f.radio_button :role, 'admin', checked: true %> Admin
      <%= f.radio_button :role, 'employee', checked: true %> Employee
    </div>

    <div class="col-md-12">
      <center><%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', employees_path, class: 'btn btn-primary' %></center>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="d-flex align-items-center justify-content-center m-5">
  <div>
    <h1 style="padding-bottom: 20px">Edit Employee</h1>
    <%= render partial: 'form', locals: {user: @employee, url: "/employees/#{@employee.id}", method_name: :patch} %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="m-5">
  <h1 style="font-weight: 400; margin-bottom: 20px">Employees
    <span class="float-end" style="margin-right: 30px">
    <%= link_to 'New Employee', new_employee_path, class: 'btn btn-outline-primary' %>
  </span>
  </h1>
  <div class="d-flex justify-content-center align-items-center">
    <table class="table" style="width: 80%">
      <thead class="table-info" style="padding-left: 15px">
      <tr>
        <th>Full Name</th>
        <th>Designation</th>
        <th>Department</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.full_name %></td>
          <td><%= employee.designation %></td>
          <td><%= employee.department.name %></td>
          <td>
            <div class="d-flex">
              <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-outline-secondary', style: 'margin-right: 10px' %>
              <%= button_to 'Delete', "/employees/#{employee.id}", method: :delete, data: { turbo_confirm: "Are you sure you want to delete?" }, class: "btn btn-outline-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/employees/new.html.erb
<div class="d-flex align-items-center justify-content-center m-5">
  <div>
    <h1 style="padding-bottom: 20px">New Employee</h1>
    <%= render partial: 'form', locals: {user: @employee, url: employees_path, method_name: :post} %>
  </div>
</div>