config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords'
  }

  # Routes for authenticated users
  authenticate :user do
    resources :departments
    resources :employees
    resources :bills do
      member do
        patch :approve
        patch :decline
      end
    end
    root 'bills#index', as: :authenticated_root
  end

  # Routes for unauthenticated users
  root 'home#index'
end

app/models/bill.rb
class Bill < ApplicationRecord
  validates_presence_of :amount, :bill_type

  belongs_to :user

  scope :by_approved, -> { where(status: self.statuses[:approved])}

  enum status: {
    pending: 'pending',
    approved: 'approved',
    rejected: 'rejected'
  }

  enum bill_type: {
    food: 'Food',
    travel: 'Travel'
  }
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?, only: %i[approve decline]
  before_action :set_bill, only: %i[show edit update destroy]

  def index
    if current_user.admin?
      @bills = Bill.all.order(created_at: :asc)
      @submitted_count = Bill.all.size
      @approved_count = Bill.all.by_approved.size
    elsif current_user.employee?
      @bills = current_user.bills.all.order(created_at: :asc)
      @submitted_count = current_user.bills.size
      @approved_count = current_user.bills.by_approved.size
    end
  end

  def show; end

  def new
    @bill = current_user.bills.new
  end

  def create
    @bill = current_user.bills.new(bill_params.merge(submission_date: Date.today))
    if @bill.save
      redirect_to bills_path, notice: 'Bill created successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    @bill.update(bill_params)
    if @bill
      redirect_to bills_path, notice: 'Bill updated successfully'
    else
      render :edit
    end
  end

  def destroy
    return if @bill.blank?

    @bill.destroy
    redirect_to bills_path, notice: 'Bill deleted successfully'
  end

  def approve
    @bill = Bill.find(params[:id])
    if @bill.update(status: Bill.statuses[:approved])
      redirect_to bills_path, notice: 'Bill approved successfully.'
    else
      redirect_to bills_path, alert: 'Failed to approve the bill.'
    end
  end

  def decline
    @bill = Bill.find(params[:id])
    if @bill.update(status: Bill.statuses[:rejected])
      redirect_to bills_path, notice: 'Bill declined successfully.'
    else
      redirect_to bills_path, alert: 'Failed to decline the bill.'
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:bill_type, :amount)
  end

  def set_bill
    @bill = current_user.bills.find_by(id: params[:id])
  end

  def is_admin?
    redirect_to bills_path notice: 'Access Denied' if current_user.employee_permission?
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true) do |form| %>
  <div class="row g-3 d-flex align-items-center justify-content-center ">

    <div class="col-md-6">
      <%= form.label :type, class: 'form-label'%><span style="color: red">*</span>
      <%= form.select :bill_type, Bill.bill_types { |k, v| v }, { prompt: 'Select Type' }, { class: 'form-control' }%>
      <% bill.errors.full_messages_for(:bill).each do |message| %>
        <p style="color: red"><%= message %></p>
    <% end %>
    </div>

    <div class="col-md-6">
      <%= form.label :amount, class: 'form-label'%><span style="color: red">*</span>
      <div class="input-group">
        <span class="input-group-text" id="basic-addon1">INR</span>
        <%= form.text_field :amount, class: 'form-control' %>
      </div>
      <% bill.errors.full_messages_for(:amount).each do |message| %>
        <p style="color: red"><%= message %></p>
      <% end %>
    </div>

    <div class="col-md-12">
      <center><%= form.submit class: 'btn btn-primary me-3' %>
        <%= link_to 'Cancel', bills_path, class: 'btn btn-primary' %></center>
    </div>
  </div>
<% end %>

app/views/bills/edit.html.erb
<div class="d-flex align-items-center justify-content-center m-5">
  <div>
    <h1 style="padding-bottom: 20px">Edit Reimbursement Form</h1>
    <%= render partial: 'form', locals: {bill: @bill} %>
  </div>
</div>

app/views/bills/index.html.erb
<div class="m-5">
  <h1 style="font-weight: 400; margin-bottom: 20px">Bills
    <% if current_user.employee? %>
      <span class="float-end" style="margin-right: 30px">
        <%= link_to 'New Bill', new_bill_path, class: 'btn btn-outline-primary ' %>
      </span>
    <% end %>
  </h1>
  <div class="d-grid align-items-center">
    <div class="row mb-3">
      <div class="col-md-6">
        <strong>Total Submitted: </strong><%= @submitted_count %>
      </div>
      <div class="col-md-6">
        <strong>Total Approved: </strong><%= @approved_count %>
      </div>
    </div>
    <table class="table" style="width: 95%">
    <thead class="table-info" style="padding-left: 15px">
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <% if current_user.admin? %>
        <th>Date of Submission</th>
      <% end %>
      <th>Submitted by</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_type %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.submission_date.strftime('%m-%d-%Y') %></td>
        <% if current_user.admin? %>
          <td><%= bill.user.full_name %></td>
        <% end %>
        <td><%= bill.status.capitalize %></td>
        <td>
          <div class="d-flex">
            <% if current_user.employee_permission? %>
              <%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-secondary', style: 'margin-right: 10px' %>
              <%= button_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% elsif current_user.admin_permission? %>
              <%= button_to 'Approve', approve_bill_path(bill), method: :patch, class: 'btn btn-outline-success', style: 'margin-right: 10px' %>
              <%= button_to 'Decline', decline_bill_path(bill), method: :patch, class: 'btn btn-outline-danger' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
  </div>
</div>

app/views/bills/new.html.erb
<div class="d-flex align-items-center justify-content-center m-5">
  <div>
    <h1 style="padding-bottom: 20px">Reimbursement Form</h1>
    <%= render partial: 'form', locals: {bill: @bill} %>
  </div>
</div>